// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI-DshdCaM8TlRxMNexpUml7rMpvlCsQc',
    appId: '1:328104110732:web:5f6dd4a1bd55c74c3ce9a9',
    messagingSenderId: '328104110732',
    projectId: 'loginapp-4b866',
    authDomain: 'loginapp-4b866.firebaseapp.com',
    storageBucket: 'loginapp-4b866.firebasestorage.app',
    measurementId: 'G-J4WCM8YQ7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZiSGd5HslNQcKKkD1FRfsTcKAhuV5DUA',
    appId: '1:328104110732:android:8ea9a23cdc6741733ce9a9',
    messagingSenderId: '328104110732',
    projectId: 'loginapp-4b866',
    storageBucket: 'loginapp-4b866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyC5-pnybomg_IDkF6qmbSlQ_wmBp7b4w',
    appId: '1:328104110732:ios:9280203f1b17eb5e3ce9a9',
    messagingSenderId: '328104110732',
    projectId: 'loginapp-4b866',
    storageBucket: 'loginapp-4b866.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyC5-pnybomg_IDkF6qmbSlQ_wmBp7b4w',
    appId: '1:328104110732:ios:9280203f1b17eb5e3ce9a9',
    messagingSenderId: '328104110732',
    projectId: 'loginapp-4b866',
    storageBucket: 'loginapp-4b866.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATZCWgHrSVKoIHYPDD20V3ELe6rB1H9fo',
    appId: '1:328104110732:web:78620e400652f1973ce9a9',
    messagingSenderId: '328104110732',
    projectId: 'loginapp-4b866',
    authDomain: 'loginapp-4b866.firebaseapp.com',
    storageBucket: 'loginapp-4b866.firebasestorage.app',
    measurementId: 'G-WDD4HYJ139',
  );
}
